-- ============================================================
--  SHROOOMS — SECURE ORDER REQUEST DATABASE MIGRATION (DAY 2 REVISED V4)
--  Paste this in: Supabase SQL Editor → Run
--  DO NOT DROP OR ALTER THE EXISTING public.orders TABLE
--  ZERO TEMPORARY TABLES OR TEMPORARY SCHEMAS USED
-- ============================================================

-- ── PREFLIGHT DETECT CHECKS (RUN TO INSPECT IF OBJECTS ALREADY EXIST) ──
-- SELECT 
--   'commerce_orders_exists' AS check_name, 
--   EXISTS (SELECT 1 FROM pg_tables WHERE schemaname = 'public' AND tablename = 'commerce_orders') AS object_exists
-- UNION ALL
-- SELECT 
--   'commerce_order_items_exists' AS check_name, 
--   EXISTS (SELECT 1 FROM pg_tables WHERE schemaname = 'public' AND tablename = 'commerce_order_items') AS object_exists
-- UNION ALL
-- SELECT 
--   'create_order_secure_exists' AS check_name, 
--   EXISTS (SELECT 1 FROM pg_proc WHERE pronamespace = 'public'::regnamespace AND proname = 'create_order_secure') AS object_exists;


-- ── 1. CREATE COMMERCE_ORDERS TABLE ──
CREATE TABLE IF NOT EXISTS public.commerce_orders (
  id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  idempotency_key  UUID NOT NULL UNIQUE,
  guest_name       TEXT NOT NULL,
  guest_email      TEXT NOT NULL,
  guest_phone      TEXT NOT NULL,
  delivery_address TEXT NOT NULL,
  items_total      NUMERIC(14,2) NOT NULL,
  status           TEXT NOT NULL DEFAULT 'Pending',
  payment_status   TEXT NOT NULL DEFAULT 'Unpaid',
  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT chk_items_total CHECK (items_total >= 0),
  CONSTRAINT chk_guest_name_len CHECK (length(trim(guest_name)) >= 1 AND length(trim(guest_name)) <= 100),
  CONSTRAINT chk_guest_email_len CHECK (length(trim(guest_email)) >= 3 AND length(trim(guest_email)) <= 254),
  CONSTRAINT chk_guest_phone_len CHECK (length(trim(guest_phone)) >= 8 AND length(trim(guest_phone)) <= 20),
  CONSTRAINT chk_delivery_address_len CHECK (length(trim(delivery_address)) >= 5 AND length(trim(delivery_address)) <= 500),
  CONSTRAINT chk_status_value CHECK (status = 'Pending'),
  CONSTRAINT chk_payment_status_value CHECK (payment_status = 'Unpaid')
);

-- Enable RLS for commerce_orders
ALTER TABLE public.commerce_orders ENABLE ROW LEVEL SECURITY;

-- Revoke all direct privileges on commerce_orders
REVOKE ALL PRIVILEGES ON public.commerce_orders FROM PUBLIC;
REVOKE ALL PRIVILEGES ON public.commerce_orders FROM anon;
REVOKE ALL PRIVILEGES ON public.commerce_orders FROM authenticated;


-- ── 2. CREATE COMMERCE_ORDER_ITEMS TABLE ──
CREATE TABLE IF NOT EXISTS public.commerce_order_items (
  id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id              UUID NOT NULL REFERENCES public.commerce_orders(id) ON DELETE CASCADE,
  product_id            TEXT NOT NULL REFERENCES public.products(_id),
  product_name_snapshot TEXT NOT NULL,
  unit_price            NUMERIC(14,2) NOT NULL,
  quantity              INTEGER NOT NULL,
  line_total            NUMERIC(14,2) NOT NULL,
  CONSTRAINT chk_unit_price CHECK (unit_price >= 0),
  CONSTRAINT chk_quantity CHECK (quantity > 0 AND quantity <= 50),
  CONSTRAINT chk_line_total CHECK (line_total >= 0)
);

-- Create single non-redundant index on foreign key
CREATE INDEX IF NOT EXISTS idx_commerce_order_items_order_id ON public.commerce_order_items(order_id);

-- Enable RLS for commerce_order_items
ALTER TABLE public.commerce_order_items ENABLE ROW LEVEL SECURITY;

-- Revoke all direct privileges on commerce_order_items
REVOKE ALL PRIVILEGES ON public.commerce_order_items FROM PUBLIC;
REVOKE ALL PRIVILEGES ON public.commerce_order_items FROM anon;
REVOKE ALL PRIVILEGES ON public.commerce_order_items FROM authenticated;


-- ── 3. CREATE SECURE ORDER TRANSACTION RPC ──
CREATE OR REPLACE FUNCTION public.create_order_secure(
  p_idempotency_key UUID,
  p_name TEXT,
  p_email TEXT,
  p_phone TEXT,
  p_address TEXT,
  p_items JSONB
)
RETURNS TABLE (
  order_request_id UUID,
  result_code TEXT
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_trimmed_name TEXT;
  v_trimmed_email TEXT;
  v_trimmed_phone TEXT;
  v_trimmed_address TEXT;
  v_order_id UUID;
  v_item RECORD;
  v_item_rec RECORD;
  v_prod_id TEXT;
  v_qty INT;
  v_prod_name TEXT;
  v_line_total_wide NUMERIC;
  v_items_total_wide NUMERIC := 0;
  v_item_count INT;
  v_distinct_count INT;
  v_matched_count INT;
  v_rows_inserted INT;
  v_normalized_items JSONB;
  v_authoritative_snapshot JSONB;
BEGIN
  -- Wrap all execution logic in a safe outer exception handler to avoid leaking database details
  BEGIN
    -- 1. Validate idempotency key
    IF p_idempotency_key IS NULL THEN
      RAISE EXCEPTION USING ERRCODE = 'P1001', MESSAGE = 'INVALID_IDEMPOTENCY_KEY';
    END IF;

    -- 2. Validate name (reject control characters)
    v_trimmed_name := trim(p_name);
    IF v_trimmed_name IS NULL OR length(v_trimmed_name) < 1 OR length(v_trimmed_name) > 100 OR v_trimmed_name ~ '[\x00-\x1F\x7F]' THEN
      RAISE EXCEPTION USING ERRCODE = 'P1002', MESSAGE = 'INVALID_NAME';
    END IF;

    -- 3. Validate email (lowercase for storage, reject control characters)
    v_trimmed_email := lower(trim(p_email));
    IF v_trimmed_email IS NULL OR length(v_trimmed_email) < 3 OR length(v_trimmed_email) > 254 OR v_trimmed_email ~ '[\x00-\x1F\x7F]' OR v_trimmed_email !~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$' THEN
      RAISE EXCEPTION USING ERRCODE = 'P1003', MESSAGE = 'INVALID_EMAIL';
    END IF;

    -- 4. Validate phone (reject control characters)
    v_trimmed_phone := trim(p_phone);
    IF v_trimmed_phone IS NULL OR length(v_trimmed_phone) < 8 OR length(v_trimmed_phone) > 20 OR v_trimmed_phone ~ '[\x00-\x1F\x7F]' OR v_trimmed_phone !~ '^[0-9+ \-()]+$' THEN
      RAISE EXCEPTION USING ERRCODE = 'P1004', MESSAGE = 'INVALID_PHONE';
    END IF;

    -- 5. Validate address (reject control characters)
    v_trimmed_address := trim(p_address);
    IF v_trimmed_address IS NULL OR length(v_trimmed_address) < 5 OR length(v_trimmed_address) > 500 OR v_trimmed_address ~ '[\x00-\x1F\x7F]' THEN
      RAISE EXCEPTION USING ERRCODE = 'P1005', MESSAGE = 'INVALID_ADDRESS';
    END IF;

    -- 6. Validate items structure and types (abuse limit: max 50 raw items)
    IF p_items IS NULL OR jsonb_typeof(p_items) != 'array' THEN
      RAISE EXCEPTION USING ERRCODE = 'P1006', MESSAGE = 'INVALID_ITEMS';
    END IF;

    v_item_count := jsonb_array_length(p_items);
    IF v_item_count < 1 THEN
      RAISE EXCEPTION USING ERRCODE = 'P1006', MESSAGE = 'INVALID_ITEMS';
    END IF;

    IF v_item_count > 50 THEN
      RAISE EXCEPTION USING ERRCODE = 'P1007', MESSAGE = 'TOO_MANY_RAW_ITEMS';
    END IF;

    -- Validate shape of each array element
    FOR v_item IN SELECT * FROM jsonb_array_elements(p_items) LOOP
      IF jsonb_typeof(v_item.value) != 'object' THEN
        RAISE EXCEPTION USING ERRCODE = 'P1008', MESSAGE = 'INVALID_ITEM_SHAPE';
      END IF;

      -- Reject unknown keys
      IF NOT (v_item.value ? 'product_id' AND v_item.value ? 'quantity') OR 
         (SELECT count(*) FROM jsonb_object_keys(v_item.value)) != 2 THEN
        RAISE EXCEPTION USING ERRCODE = 'P1008', MESSAGE = 'INVALID_ITEM_SHAPE';
      END IF;

      -- Validate product_id is text, non-empty, and rejects control characters
      v_prod_id := v_item.value->>'product_id';
      IF jsonb_typeof(v_item.value->'product_id') != 'string' OR 
         length(v_prod_id) = 0 OR 
         length(v_prod_id) > 50 OR 
         v_prod_id ~ '[\x00-\x1F\x7F]' THEN
        RAISE EXCEPTION USING ERRCODE = 'P1009', MESSAGE = 'INVALID_PRODUCT_ID';
      END IF;

      -- Validate quantity is a numeric number (integer)
      IF jsonb_typeof(v_item.value->'quantity') != 'number' THEN
        RAISE EXCEPTION USING ERRCODE = 'P1010', MESSAGE = 'INVALID_QUANTITY';
      END IF;

      -- Check integer and bounds (re-verify it's not a decimal)
      v_qty := (v_item.value->>'quantity')::numeric::integer;
      IF v_qty IS NULL OR v_qty <= 0 OR v_qty > 50 OR v_qty::numeric != (v_item.value->>'quantity')::numeric THEN
        RAISE EXCEPTION USING ERRCODE = 'P1010', MESSAGE = 'INVALID_QUANTITY';
      END IF;
    END LOOP;

    -- 7. Normalize duplicate product IDs into a local JSONB array using a clean set query
    SELECT jsonb_agg(jsonb_build_object('product_id', product_id, 'quantity', quantity)) INTO v_normalized_items
    FROM (
      SELECT (elem->>'product_id') AS product_id, sum((elem->>'quantity')::numeric::integer) AS quantity
      FROM jsonb_array_elements(p_items) AS elem
      GROUP BY (elem->>'product_id')
    ) sub;

    -- Check distinct products limit after aggregation
    v_distinct_count := jsonb_array_length(v_normalized_items);
    IF v_distinct_count > 15 THEN
      RAISE EXCEPTION USING ERRCODE = 'P1011', MESSAGE = 'TOO_MANY_ITEMS';
    END IF;

    -- Validate that aggregated quantity for any product does not exceed 50
    FOR v_item IN SELECT * FROM jsonb_array_elements(v_normalized_items) LOOP
      IF (v_item.value->>'quantity')::integer > 50 THEN
        RAISE EXCEPTION USING ERRCODE = 'P1010', MESSAGE = 'INVALID_QUANTITY';
      END IF;
    END LOOP;

    -- 8. Build one local JSONB authoritative snapshot of products and calculated prices
    -- THIS IS THE ONLY READ OF public.products IN THE ENTIRE CALL (One-Snapshot Invariant)
    SELECT jsonb_agg(
      jsonb_build_object(
        'product_id', product_id,
        'product_name', product_name,
        'unit_price', unit_price,
        'quantity', quantity,
        'line_total', line_total
      )
    ) INTO v_authoritative_snapshot
    FROM (
      SELECT 
        j.product_id,
        p.name AS product_name,
        p.price AS unit_price,
        j.quantity AS quantity,
        (p.price * j.quantity) AS line_total
      FROM public.products p
      JOIN jsonb_to_recordset(v_normalized_items) AS j(product_id TEXT, quantity INT)
        ON p._id = j.product_id
    ) sub;

    -- Verify all product IDs match exactly one authoritative product record
    v_matched_count := coalesce(jsonb_array_length(v_authoritative_snapshot), 0);
    IF v_matched_count != v_distinct_count THEN
      RAISE EXCEPTION USING ERRCODE = 'P1012', MESSAGE = 'PRODUCT_NOT_FOUND';
    END IF;

    -- 9. Perform calculations and validations over the local snapshot variable
    FOR v_item_rec IN 
      SELECT * 
      FROM jsonb_to_recordset(v_authoritative_snapshot) AS s(
        product_id TEXT,
        product_name TEXT,
        unit_price NUMERIC,
        quantity INT,
        line_total NUMERIC
      )
    LOOP
      -- Check unit price range
      IF v_item_rec.unit_price IS NULL OR v_item_rec.unit_price < 0 OR v_item_rec.unit_price >= 1000000000000.00 THEN
        RAISE EXCEPTION USING ERRCODE = 'P1013', MESSAGE = 'INVALID_PRODUCT_PRICE';
      END IF;

      -- Check line total bounds
      IF v_item_rec.line_total IS NULL OR v_item_rec.line_total < 0 OR v_item_rec.line_total >= 1000000000000.00 THEN
        RAISE EXCEPTION USING ERRCODE = 'P1014', MESSAGE = 'ORDER_TOTAL_TOO_LARGE';
      END IF;

      -- Calculate subtotal items total using wide decimal variable
      v_items_total_wide := v_items_total_wide + v_item_rec.line_total;
      IF v_items_total_wide >= 1000000000000.00 OR v_items_total_wide > 999999.99 THEN
        RAISE EXCEPTION USING ERRCODE = 'P1014', MESSAGE = 'ORDER_TOTAL_TOO_LARGE';
      END IF;
    END LOOP;

    -- 10. Concurrency Race-Safe Idempotent Insertion
    v_order_id := gen_random_uuid();
    
    INSERT INTO public.commerce_orders (
      id,
      idempotency_key,
      guest_name,
      guest_email,
      guest_phone,
      delivery_address,
      items_total,
      status,
      payment_status
    ) VALUES (
      v_order_id,
      p_idempotency_key,
      v_trimmed_name,
      v_trimmed_email,
      v_trimmed_phone,
      v_trimmed_address,
      v_items_total_wide::numeric(14,2),
      'Pending',
      'Unpaid'
    )
    ON CONFLICT (idempotency_key) DO NOTHING;

    GET DIAGNOSTICS v_rows_inserted = ROW_COUNT;

    -- If a conflict occurs, select the original ID and return ORDER_REQUEST_ALREADY_EXISTS
    IF v_rows_inserted = 0 THEN
      SELECT id INTO v_order_id
      FROM public.commerce_orders
      WHERE idempotency_key = p_idempotency_key;

      RETURN QUERY SELECT v_order_id, 'ORDER_REQUEST_ALREADY_EXISTS'::text;
      RETURN;
    END IF;

    -- 11. Insert line items (Only executed if the orders row was created in this transaction)
    -- THIS READS ONLY FROM v_authoritative_snapshot (No public.products query is executed here)
    INSERT INTO public.commerce_order_items (
      order_id,
      product_id,
      product_name_snapshot,
      unit_price,
      quantity,
      line_total
    )
    SELECT 
      v_order_id,
      s.product_id,
      s.product_name,
      s.unit_price::numeric(14,2),
      s.quantity,
      s.line_total::numeric(14,2)
    FROM jsonb_to_recordset(v_authoritative_snapshot) AS s(
      product_id TEXT,
      product_name TEXT,
      unit_price NUMERIC,
      quantity INT,
      line_total NUMERIC
    );

    -- 12. Return success status
    RETURN QUERY SELECT v_order_id, 'ORDER_REQUEST_CREATED'::text;

  EXCEPTION
    -- Catch custom validation codes and propagate them
    WHEN OTHERS THEN
      IF SQLSTATE IN ('P1001', 'P1002', 'P1003', 'P1004', 'P1005', 'P1006', 'P1007', 'P1008', 'P1009', 'P1010', 'P1011', 'P1012', 'P1013', 'P1014') THEN
        RAISE;
      ELSE
        -- Hide constraint details, stack traces, and internal schema metadata
        RAISE EXCEPTION USING ERRCODE = 'P1999', MESSAGE = 'ORDER_REQUEST_FAILED';
      END IF;
  END;
END;
$$;

-- Revoke all function execute rights from PUBLIC and authenticated roles
REVOKE ALL ON FUNCTION public.create_order_secure(UUID, TEXT, TEXT, TEXT, TEXT, JSONB) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.create_order_secure(UUID, TEXT, TEXT, TEXT, TEXT, JSONB) FROM authenticated;

-- Grant EXECUTE only to anonymous role
GRANT EXECUTE ON FUNCTION public.create_order_secure(UUID, TEXT, TEXT, TEXT, TEXT, JSONB) TO anon;
